---
infra-servers:
  hosts: 
    workstation.dumont-lab.lan:
      ansible_host: 192.168.77.27
#      ansible_connection: local
    infraserver.dumont-lab.lan:
      ansible_host: 192.168.77.21
    storage.dumont-lab.lan:
      ansible_host: 192.168.77.35  
ocp_hosts:
  hosts:
    dl360g7-1.dumont-lab.lan:
      ansible_host: 192.168.77.23
    dl360g7-2.dumont-lab.lan:
      ansible_host: 192.168.77.24
    dl360g8-3.dumont-lab.lan:
      ansible_host: 192.168.77.25
kvm_vms:
  children:
    infra_vms:
      hosts:
        ansible.dumont-lab.lan:
          ansible_host: 192.168.77.28
        dns-server.dumont-lab.lan:
          ansible_host: 192.168.77.20
        provisioner.dumont-lab.lan:
        aap-control.dumont-lab.lan:
#          ansible_host: 192.168.45.139
        aap-hub.dumont-lab.lan:
#          ansible_host: 192.168.45.140
        web-server.dumont-lab.lan:
        aap-sc.dumont-lab.lan:
        aap-sso.dumont-lab.lan:
    ocp_vms:
      hosts:
        ocp-host1.dumont-lab.lan:
          ansible_host: 192.168.45.187
        ocp-host2.dumont-lab.lan:
          ansible_host: 192.168.45.24
        ocp-host3.dumont-lab.lan:
          ansible_host: 192.168.45.25
        ocp-host4.dumont-lab.lan:
          ansible_host: 192.168.45.26
        ocp-host5.dumont-lab.lan:
          ansible_host: 192.168.45.27
        ocp-host6.dumont-lab.lan:
          ansible_host: 192.168.45.28

ipaserver:
  hosts:
    infraserver.dumont-lab.lan:
      ansible_host: 192.168.77.21
      ipaserver_domain: dumont-lab.lan
      ipaserver_realm: DUMONT-LAB.LAN
      ipaserver_setup_dns: no
      ipaadmin_password: "{{ ovirt_password }}"
      ipadm_password: "{{ ovirt_password }}"

ipaclients:
  hosts:
    provisioner.dumont-lab.lan:
    dns-server.dumont-lab.lan:
      ansible_host: 192.168.77.20
    aap-control.dumont-lab.lan:
#      ansible_host: 192.168.45.139
    aap-hub.dumont-lab.lan:
#      ansible_host: 192.168.45.140
    aap-host.dumont-lab.lan:
    web-server.dumont-lab.lan:
    kvm-host2.dumont-lab.lan:
    aap-sc.dumont-lab.lan:
    aap-sso.dumont-lab.lan:
    kvm-host1.dumont-lab.lan:

  vars:
    ipaclient_domain: dumont-lab.lan
    ipaadmin_principal: admin
    ipaadmin_password: "{{ ovirt_password }}" 
    ipaclient_mkhomedir: true

firewall:
  hosts:
    pfsense.dumont-lab.lan:
      ansible_host: 192.168.77.1


kurtvirt_hosts:
  hosts:
    vm-2022-03-01-20-23-04-1.dumont-lab.lan:
      ansible_host: 192.168.45.89
    vm-2022-03-01-01-24-06-1.dumont-lab.lan:
      ansible_host: 192.168.45.87

kvm_hosts:
  children:
    optiplex_hosts:
      hosts:
        kvm-host1.dumont-lab.lan:
          ansible_host: 192.168.45.190
        kvm-host2.dumont-lab.lan:
          ansible-host: 192.168.45.143
        aap-host.dumont-lab.lan:
          ansible_host: 192.168.45.77
    infra_hosts:
      hosts:
        infraserver.dumont-lab.lan:
          ansible_host: 192.168.77.21
        storage.dumont-lab.lan:
          ansible_host: 192.168.77.35
        aap-host.dumont-lab.lan:    
          ansible_host: 192.168.45.77

rhel7_hosts:
  hosts:
    satellite.dumont-lab.lan:
      ansible_host: 192.168.77.30

label_compliance_policy_standard:
  hosts: 
    ocp-host5.dumont-lab.lan:
      ansible_host: 192.168.45.27
    ocp-host6.dumont-lab.lan:
      ansible_host: 192.168.45.28


