- name: get machines to soe
  hosts: all
  become: true
#  remote_user: root 
  gather_facts: yes
  vars_files:
    - secrets_folder/ovirt-pass
    - vars/subscription_vars.yml

#  collections:
#    - redhat.insights 
#    - ansible.posix

  tasks:

#    - name: gather facts and ignore failuers for vm's that are off (unreachable)
 #     setup:
#      ignore_errors: yes
      
    - include_tasks: tasks/subscribe_systems.yml

    - include_tasks: tasks/soe_rhel_vm_packages.yml

    - include_role: 
        name: redhat.insights.insights_client

    - include_tasks: tasks/install_compliance.yml

#    - include_tasks: tasks/create_users_groups.yml


