- name: Get machines to soe
  hosts: all
  become: true
#  remote_user: root 
  gather_facts: yes
  vars_files:
    - secrets_folder/ovirt-pass
    - vars/subscription_vars.yml

#  collections:
#    - redhat.insights 
#    - ansible.posix

  tasks: 
    - name: Subscribe systems to satellite
      include_tasks: tasks/subscribe_systems_rhsm.yml

    - name: Install standard packages
      include_tasks: tasks/soe_rhel_vm_packages.yml

    - name: Register to insights
      include_role: 
        name: redhat.insights.insights_client

    - name: Install openscap packages
      include_tasks: tasks/install_compliance.yml

#    - include_tasks: tasks/create_users_groups.yml


