---
localhost:
  ansible_connection: local
infra-servers:
  hosts: 
    kvm-host2.dumont-lab.lan:
    kvm-host1.dumont-lab.lan:
    aap-host.dumont-lab.lan:
    kvm-host3.dumont-lab.lan:
ocp_hosts:
  hosts:
    dell-ocp.dumont-lab.lan:
kvm_vms:
  hosts:
    ansible.dumont-lab.lan:
    dns-server.dumont-lab.lan:
    provisioner.dumont-lab.lan:
    aap-control.dumont-lab.lan:
    aap-hub.dumont-lab.lan:
    idm-replica-1.dumont-lab.lan:
    idm-replica-2.dumont-lab.lan:
    sno-vm.dumont-lab.lan:
    satellite.dumont-lab.lan:


ipaserver:
  hosts:
    idm-replica-2.dumont-lab.lan:
#      ansible_host: 192.168.77.21
      ipaserver_domain: dumont-lab.lan
      ipaserver_realm: DUMONT-LAB.LAN
      ipaserver_setup_dns: no
      ipaadmin_password: "{{ ovirt_password }}"
      ipadm_password: "{{ ovirt_password }}"

ipaclients:
  hosts:
    provisioner.dumont-lab.lan:
    dns-server.dumont-lab.lan:
    aap-control.dumont-lab.lan:
    aap-hub.dumont-lab.lan:
    aap-host.dumont-lab.lan:
    kvm-host2.dumont-lab.lan:
    kvm-host1.dumont-lab.lan:
    idm-replica-1.dumont-lab.lan:
    idm-replica-2.dumont-lab.lan:
    ansible.dumont-lab.lan:
    satellite.dumont-lab.lan:
    bd-laptop.dumont-lab.lan:
    kvm-host3.dumont-lab.lan:


  vars:
    ipaclient_domain: dumont-lab.lan
    ipaadmin_principal: admin
    ipaadmin_password: "{{ ovirt_password }}" 
    ipaclient_mkhomedir: true
    ipaclient_force_join: yes

ipareplicas:
  hosts:
    idm-replica-1.dumont-lab.lan:
    idm-replica-2.dumont-lab.lan:

  vars:
    ipaadmin_password: "{{ ovirt_password }}"

label_compliance_policy_standard:
  hosts: 
    aap-sso.dumont-lab.lan:
    aap-sc.dumont-lab.lan:
    
