- name: set activation key rhel 8 virtual
  set_fact: 
    subscribe_activation_key: "{{ rhel8_ak }}"
  when: 
    - ansible_distribution_major_version == "8"
#    - inventory_hostname != "storage.dumont-lab.lan"


- name: set activation key - rhel 7
  set_fact:
    subscribe_activation_key: "rhel7-ak-vm"
  when: ansible_distribution_major_version == "7"


- name: install cert rpm
  yum:
    name: https://satellite.dumont-lab.lan/pub/katello-ca-consumer-latest.noarch.rpm
    state: present
    disable_gpg_check: yes
    validate_certs: no
  ignore_errors: yes

- name: subscribe to sat
  community.general.redhat_subscription:
    activationkey: "{{ subscribe_activation_key }}"
    org_id: "{{ org_name }}"
    rhsm_baseurl: https://satellite.dumont-lab.lan/pulp/repos
    server_hostname: satellite.dumont-lab.lan
    rhsm_repo_ca_cert: '%(ca_cert_dir)skatello-server-ca.pem'
    force_register: no
  #  auto_attach: no
  register: redhat_subscription
  ignore_errors: yes

- name: Disable all RHSM repositories
  community.general.rhsm_repository:
    name: '*'
    state: disabled
  when: redhat_subscription.changed


- name: Enable RHSM repositories
  community.general.rhsm_repository:
    name: rhel-8-for-x86_64*
    state: enabled
  when:                              
    - rhsm_repositories is not defined  
#    - ansible_distribution_major_version == "8"

- name: add foreman proxy ssh keys
  authorized_key:
    user: root
    state: present
    key: "{{ foreman_proxy_key }}"




